(declare (uses parse-input))
(declare (uses fail-safe))
(declare (uses simulate))
(use test)
(use list-utils)
(use srfi-13)
(foldl (lambda (acc name)
				 (let ((pre (file->world (string-append name ".map")))
							 (post (file->world (string-append name ".res"))))
					 (test post (simulate pre))))
			 '()
			 (command-line-arguments))
